### ISSUE TITLE
Release files are not +x'd for macOS and Linux

### ISSUE THREAD

**Issue by samualtnorman** [lifehackerhansol/YANBF#11]
otherwise, the YANBF Generator GUI just hangs forever on the first game without any sign of any error
error handling would be nice too, but that's probably a different issue

ty for the cool tool though :^)

**Comment by lifehackerhansol** [comment]
> otherwise, the YANBF Generator GUI just hangs forever on the first game without any sign of any error error handling would be nice too, but that's probably a different issue
> 
> ty for the cool tool though :^)

I... already did? At least it should be doing that within GitHub Actions itself.

This is actually a bug that needs to be fixed. Thanks for reporting.

**Comment by lifehackerhansol** [comment]
@samualtnorman can you please check if this is properly chmodded? https://nightly.link/lifehackerhansol/YANBF/workflows/nightly/main

**Comment by samualtnorman** [comment]
still getting `zsh: permission denied: ./generator`
are you sure the "is executable" flag even survives being zipped and unzipped?

**Comment by lifehackerhansol** [comment]
My guess is that it isn't.

Which is a problem. How do I make this simple for the average user lol.

**Comment by samualtnorman** [comment]
the GUI didn't require me to change any permissions on it, so maybe your best bet is to get the GUI tool to `chmod +x` the files on startup

**Comment by Yrouel** [comment]
What are you using to build the final release? I just tried and the zip utility on mac does preserve the unix permissions upon unzipping.
Perhaps see if you can change utility on your side or find the option to specifically preserve the flags

**Comment by lifehackerhansol** [comment]
I directly upload to GitHub via its API. This is not really a ZIP issue but rather a GitHub issue.

I can double zip the releases, I guess. That shouldn't be that difficult for people, right?

**Comment by lifehackerhansol** [comment]
This was fixed by double zipping the release for macOS and Linux.
