### ISSUE TITLE
DNS setting issues

### ISSUE THREAD

**Issue by teddblue** [lifehackerhansol/YANBF#13]
This isn't necessarily an issue with this forwarder specifically, but with forwarders in general. When I load a game like Pokémon black from twilight menu, it will be compatible with my custom DNS settings, but when using a forwarder it seemingly ignores the custom DNS. Any help would be much appreciated

**Comment by lifehackerhansol** [comment]
This is an nds-bootstrap issue.

Please join DSi Mode Hacking Discord server for assistance with that matter: https://ds-homebrew.com/discord.html
