### ISSUE TITLE
Confused on how to get widescreen working

### ISSUE THREAD

**Issue by AftDawn** [lifehackerhansol/YANBF#17]
i have tried searching online for how to get widescreen working, i have TWPatch installed and a widescreen .cxi file made, but i don't know where to put it, or if i need it at all

i do have `apfix.pck` and `widescreen.pck` in the right spot

i need help

**Comment by nandolawson** [comment]
Afaik this only works with TWLM+. Not sure if this is right.

**Comment by AftDawn** [comment]
Oh, I thought that this also has support cause of #3

**Comment by lifehackerhansol** [comment]
widescreen.cxi goes in the ntr-forwarder folder, alongside the apfix/widescreen.pck stuff.

**Comment by AftDawn** [comment]
Ah, thank you
