### ISSUE TITLE
Python 3.10 breaks YANBF

### ISSUE THREAD

**Issue by Minehors** [lifehackerhansol/YANBF#6]
the logs constantly sais python not correct it is correct installed and it.

I did everything you said in your readme folder but your program aka software is not working correctly. I even have python double installed (trying if it would fix not two installs on one pc)

here log file : 

Tue Feb 22 2022 19:38:36 GMT+0100 (Midden-Europese standaardtijd): Python is niet gevonden. Voer zonder argumenten uit om te installeren vanuit de
Tue Feb 22 2022 19:38:36 GMT+0100 (Midden-Europese standaardtijd):  Microsoft Store of schakel deze snelkoppeling uit via Instellingen > Aliassen voor app-uitvoering beheren.

Tue Feb 22 2022 19:47:53 GMT+0100 (Midden-Europese standaardtijd): More than one ID0 folder detected. Please remove unnecessary ID0 folders before continuing.

Tue Feb 22 2022 19:49:09 GMT+0100 (Midden-Europese standaardtijd): Python is niet gevonden. Voer zonder argumenten uit om te 

it says no python it is working phtyon is working for other scripts and tools

**Comment by lifehackerhansol** [comment]
Try setting the Python argument to something other than `py -3`. There should be a couple different options in the GUI.

Maybe also check if it works from Command Prompt rather than the GUI.

**Comment by Minehors** [comment]
So how do i do that then with cmd instead of the GUI?

**Comment by Minehors** [comment]
Wed Feb 23 2022 19:39:32 GMT+0100 (Midden-Europese standaardtijd): More than one ID0 folder detected. Please remove unnecessary ID0 folders before continuing.

![what is this](https://user-images.githubusercontent.com/39132371/155385886-0e861ebc-1007-4404-a0b8-533a83a69050.PNG)

**Comment by lifehackerhansol** [comment]
It seems this structure is missing the Private folder. I did not anticipate that possibility. 

I'll make a fix for this in a bit.

**Comment by lifehackerhansol** [comment]
[build (1).zip](https://github.com/lifehackerhansol/YANBF/files/8134769/build.1.zip)

I think I've fixed the detection. Can you retry with this folder?

makerom.exe and bannertool.exe will be missing in this ZIP. You can copy them from the release ZIP file.

**Comment by Minehors** [comment]
Any idea what i did wrong i copy't everything you said and in cmd in the foler where the genertaor is located and also showed to script where my converted nds file is????

Do i need to do it like this ``F:\nds_roms\Pokemon_Platinum\Pokemon - Platinum Version (USA).nds´´ or does that not make a difrence



C:\Users\mycdrive\Downloads\Compressed\build.1\YANBF\generator>py generator.py F:\nds_roms\Pokemon_Platinum
Extracting and resizing icon...
Traceback (most recent call last):
  File "C:\Users\mycdrive\Downloads\Compressed\build.1\YANBF\generator\generator.py", line 76, in <module>
    core.makeicon(path)
  File "C:\Users\mycdrive\Downloads\Compressed\build.1\YANBF\generator\core.py", line 125, in makeicon
    im = bannergif(path)
  File "C:\Users\mycdrive\Downloads\Compressed\build.1\YANBF\generator\bannergif.py", line 30, in bannergif
    rom = open(path, "rb")
PermissionError: [Errno 13] Permission denied: 'F:\\nds_roms\\Pokemon_Platinum'

**Comment by lifehackerhansol** [comment]
You need to give the direct path to the ROM itself, not the folder.

**Comment by Minehors** [comment]
idk what you mean bcs i tryed everything i get is Permission denied: and i did run the command with just the rood from the sdcard nothing happends at all in the cmd be more spesific or write the command i need to do so i can try and copy paste it.

So the rom is located "F:\nds_roms\Pokemon_Platinum" and it gives always an error you say dont use the folder but thats a PATH right where its stored how is cmd gonnan know that he has to make a cia for that specific file then?

**Comment by lifehackerhansol** [comment]
After discussion on Discord it appears support for Python 3.10 is broken.

This will likely be resolved after moving to executable binaries.

**Comment by lifehackerhansol** [comment]
Python has been completely removed. Next release will not have this issue.
