### ISSUE TITLE
cant get the right file path

### ISSUE THREAD

**Issue by ghost** [lifehackerhansol/YANBF#68]
i have a n3ds which as you may know is super annoying to repeatedly remove the sd card.
im trying to use the gui thing and input the right file path, without the sd card inserted, so i can transfer the forwarder with ftpd.
but no matter what file path i put in there, it cant find the rom after i install the forwarder.
pls help.

one example
"D:\roms\nds\Super Mario 64 DS.nds"

**Comment by ghost** [comment]
yes i did see the POSIX thing, idk what that is but i tried to edit the path to match it and i couldnt get it to work

**Comment by ceretical23489** [comment]
edit: couldnt
sorry for clutter

**Comment by ghost** [comment]
Hello I recently found a closed issue:
https://github.com/YANBForwarder/YANBF/issues/37
That's the first thing I tried, but I tried it again and it still didn't work
Pls help pls pls pls

**Comment by ghost** [comment]
Please help me 
I beg for help
I've literally cried two times trying to get this to work
I beg

**Comment by ghost** [comment]
ok im gonna go step by step my process and whats going wrong
1. ensure i have the rom on my sd card and pc, with the exact same file name
2. open yanbf-gui-.exe
3. click the folder icon
4. right click the rom on my sd card and copy the path:       "D:\roms\nds\Newer Super Mario Bros. DS.nds"
5. close the file select and reopen it
6. open the copy of the file with the exact same name on my desktop
7. set box art and sound.
8. since i opened the desktop file and not the sd card one, the file would have the wrong path. In ROM PATH, i paste in:      "D:\roms\nds\Newer Super Mario Bros. DS.nds"
9. click the download icon
10. transfer the Newer Super Mario Bros. DS.nds.cia to my sd cards cias folder
11. reinsert sd card into 3ds, install cia file with fbi
12. return to home menu and open the new shortcut
13. error message

Not found:
sd:"D:\roms\nds\Newer Super Mario Bros. DS.nds"

Please recreate the forwarder with the correct ROM path.

Press B to return to the home menu.

14. try not to cry a thrid time

i have been changing the file path to everything i can think of and it still not work 
PLEASE HELP ME

**Comment by ghost** [comment]
i figured it out
the fuckery is in the slashes
to anyone trying this heres an example

SD card path: "D:\roms\nds\Newer Super Mario Bros. DS.nds"
try this: /roms/nds/Newer Super Mario Bros. DS.nds

**Comment by ghost** [comment]
lifehackerhansol, i ask that this tip be on the main page of this and the gbatempt page because i cant be the one person who had trouble with this

also i have windows 11 if that made a difference

**Comment by lifehackerhansol** [comment]
Sorry, just got around to looking at this.

> i figured it out the fuckery is in the slashes to anyone trying this heres an example
> 
> SD card path: "D:\roms\nds\Newer Super Mario Bros. DS.nds" try this: /roms/nds/Newer Super Mario Bros. DS.nds

What you are explaning here is exactly what a POSIX file path looks like. It is on the README file as well as the GBATemp forum post at step 2 of "Using the command-line program" and step 3 of "Using the graphical user interface", and even provides the _exact_ example you specified.

Unfortunately by design of 3DS homebrew development I cannot make this any easier for Windows users, but the instructions for the issue you had _were_, and are, still there.

**Comment by ghost** [comment]
Sorry I didn't know what posix was and thought the different slash was a typo
