### ISSUE TITLE
Animated DSi Icons Importing only 1 Frame

### ISSUE THREAD

**Issue by TenkaDigi** [lifehackerhansol/YANBF#81]
For example, the Pokémon BW/B2W2 games include animated icons, as does Brain Age Express. These game icons should be able to animate on the 3DS Home Menu.

**Comment by lifehackerhansol** [comment]
3DS titles (and by definition whatever YANBF spits out) do not support animated icons.

I do think it's weird that DSi-Enhanced/DSiWare supports it but 3DS titles don't, but that's the reality we live in, I suppose.
