### ISSUE TITLE
Option for custom sound file

### ISSUE THREAD

**Issue by Yrouel** [lifehackerhansol/YANBF#9]
At the moment the generator only offers the possibility to chose a custom banner png and uses the builtin dsboot.wav as default for every cia.
It would be nice to also have the option to specify a custom wav file.

My workaround has been to temporarily replace dsboot.wav but you know...

**Comment by lifehackerhansol** [comment]
I can implement this in CLI. I don't think I can make an option in the GUI though, because I suck at web dev and the GUI is built on Electron.
